// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Homelab',
      items: [{ type: 'autogenerated', dirName: 'homelab' }]
    },
    {
      type: 'category',
      label: 'OpenStack',
      items: [{ type: 'autogenerated', dirName: 'openstack' }]
    }
  ]
}

export default sidebars
