// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Proxmox',
      items: [{ type: 'autogenerated', dirName: 'proxmox' }]
    },
    {
      type: 'category',
      label: 'OpenStack',
      items: [{ type: 'autogenerated', dirName: 'openstack' }]
    },
    {
      type: 'category',
      label: 'Keycloak',
      items: [{ type: 'autogenerated', dirName: 'keycloak' }]
    },
    {
      type: 'category',
      label: 'Nextcloud',
      items: [{ type: 'autogenerated', dirName: 'nextcloud' }]
    },
    {
      type: 'category',
      label: 'Vaultwarden',
      items: [{ type: 'autogenerated', dirName: 'vaultwarden' }]
    },
  ]
}

export default sidebars
